#!/usr/bin/env python3.6

""" A simple webnovel crawler."""
# TODO: 1.考虑exception问题 2.多线程？

import undetected_chromedriver as uc
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import urllib.request
import time
import os
import re


def namemodifier(string):
    string = string.replace('\\','')
    string = string.replace('/','')
    string = string.replace(':','')
    string = string.replace('*','')
    string = string.replace('"','')
    string = string.replace('<','')
    string = string.replace('>','')
    string = string.replace('|','')
    string = string.replace('?','')
    return string


def now():
    t = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    return t+' '


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        link = sys.argv[1]
    else:
        while True:
            print('Enter the absolute URL of the cover page of the novel or comic that you want to download')
            print('Example (Novel): https://www.webnovel.com/book/8335353205000005/Mystical-Journey')
            print('Example (Comic): https://www.webnovel.com/comic/cultivation-chat-group_11609847806441001')
            link = input()
            if 'www.webnovel.com/book' in link or 'www.webnovel.com/comic' in link:
                break
            print('Please double check your URL.')

    is_comic = 'www.webnovel.com/comic' in link

    if is_comic:
        # get the table of contents for comic
        print(now()+'Initializing the virtual browser for comic... Might take a while')
        options = uc.ChromeOptions()
        browser = uc.Chrome(options=options, version_main=148)
        browser.get(link)
        booktitle = namemodifier(browser.title.split(' - ')[0])
        print(now()+'Comic name: %s' % booktitle)
        
        comic_slug = ""
        slug_match = re.search(r'/comic/([^/]+)', link)
        if slug_match:
            comic_slug = slug_match.group(1).split('?')[0].split('#')[0]

        comic_id_match = re.search(r'_(\d+)', link)
        if comic_id_match:
            catalog_link = f"https://www.webnovel.com/comic/{comic_id_match.group(1)}/catalog"
        else:
            catalog_link = link + "/catalog"
            
        print(now()+'Loading catalog page...')
        browser.get(catalog_link)
        time.sleep(8)
        
        links = []
        seen = set()
        for a in browser.find_elements(By.TAG_NAME, "a"):
            try:
                href = a.get_attribute("href") or ""
                text = a.text.strip().replace('\n', ' ')
                if comic_slug and f"/comic/{comic_slug}/" in href:
                    parts = href.split(f"/comic/{comic_slug}/")
                    if len(parts) > 1:
                        chap_id = parts[1].split('?')[0].split('#')[0]
                        if chap_id and chap_id[0].isdigit():
                            if href not in seen:
                                seen.add(href)
                                links.append((href, text))
            except Exception:
                pass
                
        print(now()+'Found %d chapters' % len(links))
        
        # Start download
        if not os.path.exists(booktitle):
            os.mkdir(booktitle)
        os.chdir(booktitle)
        readme = open('readme.log','a+',encoding='utf-8')
        readme.write('Comic name: '+booktitle+'\n')
        readme.write('© Webnovel\n')
        readme.write('Generated by Webnovel Comic Crawler at '+now()+'\n')
        readme.close()
        
        if not os.path.exists('chapters'):
            os.mkdir('chapters')
        os.chdir('chapters')
        
        for chap_url, chap_text in links:
            chap_title = namemodifier(chap_text or chap_url.split('/')[-1])
            if not chap_title:
                chap_title = chap_url.split('/')[-1]
            
            # Skip if already downloaded and not empty
            if os.path.exists(chap_title) and os.path.isdir(chap_title):
                if len(os.listdir(chap_title)) > 0:
                    print(now()+'Skipping already downloaded chapter: %s' % chap_title)
                    continue
                
            print(now()+'Loading chapter: %s' % chap_title)
            try:
                browser.get(chap_url)
                time.sleep(5)
            except Exception as e:
                print(now()+'Error loading page for chapter %s: %s' % (chap_title, e))
                try:
                    browser.title
                except Exception:
                    print(now()+'Browser session dead. Restarting Chrome...')
                    try:
                        browser.quit()
                    except Exception:
                        pass
                    browser = uc.Chrome(options=options, version_main=148)
                    try:
                        browser.get(chap_url)
                        time.sleep(5)
                    except Exception as e2:
                        print(now()+'Failed to recover and load chapter %s: %s' % (chap_title, e2))
                        continue
            
            # Extract images
            try:
                imgs = browser.find_elements(By.TAG_NAME, "img")
                img_urls = []
                for img in imgs:
                    try:
                        src = img.get_attribute("data-original") or img.get_attribute("data-src") or img.get_attribute("src") or ""
                        if "comicpage" in src or "comic-image" in src:
                            if src not in img_urls:
                                img_urls.append(src)
                    except Exception:
                        pass
            except Exception as e:
                print(now()+'Failed to find images on page: %s' % e)
                continue
                    
            if not img_urls:
                print(now()+'No images found for chapter: %s' % chap_title)
                continue
                
            if not os.path.exists(chap_title):
                os.mkdir(chap_title)
            os.chdir(chap_title)
            
            for idx, img_url in enumerate(img_urls, 1):
                file_name = f"{idx:03d}.jpg"
                req = urllib.request.Request(
                    img_url,
                    headers={
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Referer': 'https://www.webnovel.com/'
                    }
                )
                try:
                    with urllib.request.urlopen(req) as response:
                        data = response.read()
                        with open(file_name, "wb") as f_img:
                            f_img.write(data)
                except Exception as e:
                    print(now()+'Failed to download image %s: %s' % (file_name, e))
                    
            print(now()+'Downloaded chapter: %s' % chap_title)
            os.chdir('..')
            
        try:
            browser.quit()
        except Exception:
            pass
        print('Work complete!')
        os.chdir('..\..')
        os.startfile(booktitle)

    else:
        # get the table of contents for book
        print(now()+'Initializing the virtual browser... Might take a while')
        options = Options()
        options.add_argument("--headless")
        browser = webdriver.Edge(options=options)
        browser.get(link)
        booktitle = namemodifier(browser.title.split(' - ')[0])
        print(now()+'Book name: %s' % booktitle)
        print(now()+'Locating the contents page...')
        browser.find_element(By.CLASS_NAME, 'j_show_contents').click()
        time.sleep(5)
        pattern = re.compile(r'''<p class="ell dib vam">.*?>.*?>(.*?)<.*?</strong>.*?>(.*?)<.*?</strong>.*?>(.*?)<''',re.S)
        bookinfo = re.findall(pattern,browser.page_source)[0]
        contents = browser.find_elements(By.XPATH, "//a[@class='c_strong vam ell db pr']")
        print(now()+'Retrieving table of contents')
        links = [i.get_attribute('href') for i in contents]
        browser.quit()

        # start real work
        os.mkdir(booktitle)
        os.chdir(booktitle)
        book = open(booktitle+'.txt','a+',encoding='utf-8')
        readme = open('readme.log','a+',encoding='utf-8')
        os.mkdir('chapters')
        os.chdir('chapters')
        for link in links:
            page = urllib.request.urlopen(link)
            soup = BeautifulSoup(page,'html5lib')
            title = namemodifier(soup.find(name='div', attrs={'class': "cha-tit"}).h3.string)
            cont = soup.find(name='div', attrs={'class': "cha-words"}).find_all(name='p')
            book.write(title+'\n')
            with open(title+'.txt','a+',encoding='utf-8') as f:
                for i in cont:
                    try:
                        text = i.get_text()
                        text = text.strip()
                        if text == '\n' or text == '':
                            continue
                        elif not text.endswith('\n'):
                            text = text + '\n'
                        f.write(text)
                        book.write(text)
                    except (TypeError,AttributeError):
                        pass
            print(now()+'Downloading %s' % title)
            time.sleep(0.1)
        book.close()

        # write logs
        readme.write('Book name: '+booktitle+'\n')
        readme.write('Original Author: '+bookinfo[0]+'\n')
        readme.write('Translator: '+bookinfo[1]+'\n')
        readme.write('Editor: '+bookinfo[2]+'\n')
        readme.write('\n')
        readme.write('© 2017 Webnovel\n')
        readme.write('Generated by Webnovel Crawler at '+now())
        readme.close()

        # Done!
        print('Work complete!')
        os.chdir('..\..')
        os.startfile(booktitle)
